### ISSUE TITLE
WebApp blank, Incorrect ACL setting for Google Cloud Bucket

### ISSUE THREAD

**Issue by mixuala** [nottombrown/rl-teacher#37]
I followed the install/usage script closely and was able to get the demo to work. However, I had a problem with ACLs for the videos uploaded to Google Cloud

I used these commands to create my GCS Bucket
```
export RL_TEACHER_GCS_BUCKET="gs://rl-teacher-<YOUR_NAME>"
gsutil mb $RL_TEACHER_GCS_BUCKET
gsutil defacl ch -u AllUsers:R $RL_TEACHER_GCS_BUCKET
```

But the files in the bucket were not accessible to `AllUsers`.  The `human-feedback-api webapp` would only display blanks where the videos were to appear. I went back and ran this command to allow `AllUsers:R`

```
gsutil acl ch -u AllUsers:R $RL_TEACHER_GCS_BUCKET
```

**Comment by nottombrown** [comment]
Interesting. Does this resolve #36 ? If so, please make a PR to update the README with the correct commands. Thanks!

**Comment by mixuala** [comment]
It's the opposite,  https://github.com/nottombrown/rl-teacher/issues/36, resolves this bug.  Perhaps the GCP bucket error message was not accurate
